
package co.com.activos.jrhu0055.carpeta_ms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "carpeta_msPortType", targetNamespace = "http://tempuri.org/carpeta_ms")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarpetaMsPortType {


    /**
     * 
     * @param reqCrear
     * @return
     *     returns org.tempuri.carpeta_ms.ResCrear
     * @throws CrearCarpetaFault1
     */
    @WebMethod(operationName = "CrearCarpeta", action = "crearCarpeta")
    @WebResult(name = "ResCrear",
            targetNamespace = "http://tempuri.org/carpeta_ms", partName = "ResCrear")
    ResCrear crearCarpeta(
        @WebParam(name = "ReqCrear", targetNamespace = "http://tempuri.org/carpeta_ms",mode = WebParam.Mode.OUT, partName = "ReqCrear")
        ReqCrear reqCrear)
        throws CrearCarpetaFault1
    ;

}
