
package co.com.activos.jrhu0055.carpeta_ms;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ErrorMessage", targetNamespace = "http://tempuri.org/carpeta_ms")
public class CrearCarpetaFault1
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ErrorMessage faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CrearCarpetaFault1(String message, ErrorMessage faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CrearCarpetaFault1(String message, ErrorMessage faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.tempuri.carpeta_ms.ErrorMessage
     */
    public ErrorMessage getFaultInfo() {
        return faultInfo;
    }

}
